# taken from padeopsIO
# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

readme = ''

setup(
    long_description=readme,
    name='sobol',
    version='0.1.0',
    description='Calculating sobol indices',
    python_requires='>=3.7',
    author='Kerry Klemmer',
    author_email='ksklemmer@gmail.com',
    license='MIT',
    packages=['sobol'],
    package_dir={"": "."},
    package_data={},
    install_requires=[],
)